name: deploy-toy-website

on: [push]

permissions:
  id-token: write
  contents: read

env:
  RESOURCEGROUP_NAME: 20240305-actions-rg
  ENVIRONMENT: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/rg.bicep
          parameters: rgName=${{ env.RESOURCEGROUP_NAME }}
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.RESOURCEGROUP_NAME }}
          template: ./deploy/main.bicep
          parameters: environmentType=${{env.ENVIRONMENT}}